# Generated by Django 3.2.6 on 2021-09-07 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='favmovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dname', models.CharField(max_length=500)),
                ('imdb', models.FloatField(default=1.0)),
                ('earn', models.IntegerField()),
                ('image', models.ImageField(default='', upload_to='favmovie\\images')),
                ('rdate', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(default='holly', max_length=50)),
            ],
        ),
    ]
